/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Redirect = {
  _id: string;
  _type: "redirect";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  source: string;
  destination: string;
  permanent?: boolean;
  isEnabled?: boolean;
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  quote: string;
  author: string;
  role?: string;
  company?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  companyLogo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  featured?: boolean;
  order?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Faq = {
  _id: string;
  _type: "faq";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  question: string;
  answer: BlockContent;
  category?: "general" | "services" | "support" | "billing";
  order?: number;
};

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href?: string;
    blank?: boolean;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
} | {
  asset?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
  };
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt: string;
  caption?: string;
  _type: "image";
  _key: string;
}>;

export type TeamMember = {
  _id: string;
  _type: "teamMember";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  role: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  bio?: BlockContent;
  location?: string;
  email?: string;
  socialLinks?: Array<{
    _key: string;
  } & SocialLink>;
  order?: number;
  isActive?: boolean;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type SupportPage = {
  _id: string;
  _type: "supportPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  eyebrow?: string;
  title: string;
  titleHighlight?: string;
  description?: string;
  teamViewerUrl: string;
  teamViewerTitle?: string;
  seo?: Seo;
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  noIndex?: boolean;
  canonicalUrl?: string;
};

export type ServicesPage = {
  _id: string;
  _type: "servicesPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  eyebrow?: string;
  title: string;
  titleHighlight?: string;
  description?: string;
  seo?: Seo;
};

export type PrivacyPolicyPage = {
  _id: string;
  _type: "privacyPolicyPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  eyebrow?: string;
  title: string;
  titleHighlight?: string;
  lastUpdated?: string;
  body: BlockContent;
  seo?: Seo;
};

export type TermsOfServicePage = {
  _id: string;
  _type: "termsOfServicePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  eyebrow?: string;
  title: string;
  titleHighlight?: string;
  lastUpdated?: string;
  body: BlockContent;
  seo?: Seo;
};

export type OurTeamPage = {
  _id: string;
  _type: "ourTeamPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  headerEyebrow?: string;
  headerTitle?: string;
  headerTitleHighlight?: string;
  headerDescription?: string;
  seo?: Seo;
};

export type Homepage = {
  _id: string;
  _type: "homepage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroHeadlinePart1?: string;
  heroHighlightWord?: string;
  heroHeadlinePart2?: string;
  heroDescription?: string;
  heroPrimaryCta?: {
    label?: string;
    href?: string;
  };
  heroSecondaryCta?: {
    label?: string;
    href?: string;
  };
  servicesTitle?: string;
  servicesDescription?: string;
  serviceCards?: Array<{
    title: string;
    description?: string;
    href?: string;
    ctaLabel?: string;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    _key: string;
  }>;
  seo?: Seo;
};

export type ContactPage = {
  _id: string;
  _type: "contactPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  eyebrow?: string;
  title: string;
  heading?: string;
  description?: string;
  responseTimeText?: string;
  contactLabels?: {
    addressLabel?: string;
    phoneLabel?: string;
    emailLabel?: string;
  };
  formSettings?: {
    submitButtonText?: string;
    successTitle?: string;
    successMessage?: string;
    privacyText?: string;
    privacyLinkText?: string;
    privacyLinkUrl?: string;
    privacyAfterText?: string;
  };
  seo?: Seo;
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  headerEyebrow?: string;
  headerTitle?: string;
  headerTitleHighlight?: string;
  heroTitle: string;
  heroSubtitle?: string;
  heroImages?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  enableFullWidthImage?: boolean;
  fullWidthImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  missionTitle?: string;
  missionIntro?: string;
  missionBody?: string;
  stats?: Array<{
    label: string;
    value: string;
    postfix?: string;
    _key: string;
  }>;
  teamTitle?: string;
  teamDescription?: string;
  seo?: Seo;
};

export type Navigation = {
  _id: string;
  _type: "navigation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  mainNav?: Array<{
    _key: string;
  } & NavItem>;
  ctaButton?: {
    label?: string;
    link?: Link;
  };
  footerColumns?: Array<{
    _key: string;
  } & FooterColumn>;
  legalLinks?: Array<{
    _key: string;
  } & Link>;
};

export type Link = {
  _type: "link";
  label: string;
  linkType: "internal" | "external";
  internalLink?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "page";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "service";
  };
  externalUrl?: string;
  openInNewTab?: boolean;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteName: string;
  logo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  favicon?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  defaultSeo?: Seo;
  contact?: {
    phone?: string;
    email?: string;
    address?: string;
    businessHours?: string;
  };
  socialLinks?: Array<{
    _key: string;
  } & SocialLink>;
  localBusiness?: {
    businessType?: "LocalBusiness" | "ProfessionalService" | "ComputerStore" | "Organization";
    legalName?: string;
    description?: string;
    streetAddress?: string;
    city?: string;
    region?: string;
    postalCode?: string;
    country?: string;
    latitude?: number;
    longitude?: number;
    priceRange?: "$" | "$$" | "$$$";
    openingHours?: Array<string>;
    serviceArea?: Array<string>;
    foundingDate?: string;
    numberOfEmployees?: number;
  };
  analytics?: {
    googleAnalyticsId?: string;
    googleTagManagerId?: string;
  };
  contactSection?: {
    heading?: string;
    subheading?: string;
    ctaLabel?: string;
    ctaLink?: string;
  };
};

export type RichText = {
  _type: "richText";
  title?: string;
  body: BlockContent;
  maxWidth?: "prose" | "md" | "lg" | "full";
  alignment?: "left" | "center";
};

export type ContactSection = {
  _type: "contactSection";
  title?: string;
  subtitle?: string;
  showContactForm?: boolean;
  showContactInfo?: boolean;
  showMap?: boolean;
  backgroundColor?: "default" | "accent" | "dark";
};

export type FaqSection = {
  _type: "faqSection";
  title?: string;
  subtitle?: string;
  faqs?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "faq";
  }>;
  filterByCategory?: "" | "general" | "services" | "support" | "billing";
  limit?: number;
  showContactCta?: boolean;
};

export type StatsSection = {
  _type: "statsSection";
  title?: string;
  subtitle?: string;
  stats?: Array<{
    _key: string;
  } & Stat>;
  backgroundColor?: "default" | "accent" | "dark";
};

export type TeamGrid = {
  _type: "teamGrid";
  title?: string;
  subtitle?: string;
  teamMembers?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "teamMember";
  }>;
  limit?: number;
  showBio?: boolean;
  columns?: 2 | 3 | 4;
};

export type ServicesGrid = {
  _type: "servicesGrid";
  title?: string;
  subtitle?: string;
  services?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "service";
  }>;
  showAllLink?: boolean;
  columns?: 2 | 3 | 4;
};

export type Hero = {
  _type: "hero";
  title: string;
  subtitle?: string;
  backgroundImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  cta?: Array<{
    label: string;
    link?: Link;
    variant?: "primary" | "secondary" | "outline";
    _type: "ctaButton";
    _key: string;
  }>;
  alignment?: "left" | "center" | "right";
  size?: "sm" | "md" | "lg" | "full";
};

export type FooterColumn = {
  _type: "footerColumn";
  title: string;
  links?: Array<{
    _key: string;
  } & Link>;
};

export type NavItem = {
  _type: "navItem";
  label: string;
  link?: Link;
  children?: Array<{
    label: string;
    link?: Link;
    _type: "childNavItem";
    _key: string;
  }>;
};

export type Feature = {
  _type: "feature";
  title: string;
  description?: string;
  icon?: string;
};

export type Stat = {
  _type: "stat";
  value: string;
  suffix?: string;
  label: string;
};

export type SocialLink = {
  _type: "socialLink";
  platform: "facebook" | "linkedin" | "twitter" | "instagram" | "youtube" | "github";
  url: string;
};

export type Service = {
  _id: string;
  _type: "service";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  shortDescription: string;
  icon?: string;
  featuredImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  order?: number;
  heroImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  tagline: string;
  taglineHighlight?: string;
  subtitle?: string;
  introText?: string;
  introHighlights?: Array<string>;
  bodyContent?: BlockContent;
  benefitsTitle?: string;
  benefitsHighlight?: string;
  benefits?: Array<{
    title: string;
    description?: string;
    icon?: string;
    _type: "benefit";
    _key: string;
  }>;
  servicesTitle?: string;
  servicesTitleHighlight?: string;
  serviceItems?: Array<string>;
  faqTitle?: string;
  faqTitleHighlight?: string;
  faqs?: Array<{
    question: string;
    answer: string;
    _type: "faqItem";
    _key: string;
  }>;
  contactCta?: {
    enabled?: boolean;
    heading?: string;
    buttonText?: string;
    buttonLink?: string;
  };
  ctaHeadline?: string;
  ctaHighlight?: string;
  ctaSubtext?: string;
  ctaButtonText?: string;
  ctaButtonLink?: string;
  relatedServices?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "service";
  }>;
  features?: Array<{
    _key: string;
  } & Feature>;
  body?: BlockContent;
  seo?: Seo;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  pageBuilder?: Array<{
    _key: string;
  } & Hero | {
    _key: string;
  } & ServicesGrid | {
    _key: string;
  } & TeamGrid | {
    _key: string;
  } & StatsSection | {
    _key: string;
  } & FaqSection | {
    _key: string;
  } & ContactSection | {
    _key: string;
  } & RichText>;
  seo?: Seo;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = Redirect | Testimonial | SanityImageCrop | SanityImageHotspot | Faq | BlockContent | TeamMember | Slug | SupportPage | Seo | ServicesPage | PrivacyPolicyPage | TermsOfServicePage | OurTeamPage | Homepage | ContactPage | AboutPage | Navigation | Link | SiteSettings | RichText | ContactSection | FaqSection | StatsSection | TeamGrid | ServicesGrid | Hero | FooterColumn | NavItem | Feature | Stat | SocialLink | Service | Page | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/app/sitemap.ts
// Variable: SITEMAP_SERVICES_QUERY
// Query: *[_type == "service" && defined(slug.current)] | order(title asc) {    "slug": slug.current,    _updatedAt  }
export type SITEMAP_SERVICES_QUERYResult = Array<{
  slug: string;
  _updatedAt: string;
}>;

// Source: ./src/sanity/lib/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0]{    siteName,    logo,    favicon,    "defaultSeo": {      "title": coalesce(defaultSeo.title, siteName),      "description": defaultSeo.description,      "image": defaultSeo.image,      "noIndex": defaultSeo.noIndex == true    },    contact {      phone,      email,      address,      businessHours    },    socialLinks[] {      _key,      platform,      url    },    analytics {      googleAnalyticsId,      googleTagManagerId    },    contactSection {      heading,      subheading,      ctaLabel,      ctaLink    },    localBusiness {      businessType,      legalName,      description,      streetAddress,      city,      region,      postalCode,      country,      latitude,      longitude,      priceRange,      openingHours,      serviceArea,      foundingDate,      numberOfEmployees    }  }
export type SITE_SETTINGS_QUERYResult = {
  siteName: string;
  logo: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  favicon: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  defaultSeo: {
    title: string;
    description: string | null;
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    noIndex: boolean | false;
  };
  contact: {
    phone: string | null;
    email: string | null;
    address: string | null;
    businessHours: string | null;
  } | null;
  socialLinks: Array<{
    _key: string;
    platform: "facebook" | "github" | "instagram" | "linkedin" | "twitter" | "youtube";
    url: string;
  }> | null;
  analytics: {
    googleAnalyticsId: string | null;
    googleTagManagerId: string | null;
  } | null;
  contactSection: {
    heading: string | null;
    subheading: string | null;
    ctaLabel: string | null;
    ctaLink: string | null;
  } | null;
  localBusiness: {
    businessType: "ComputerStore" | "LocalBusiness" | "Organization" | "ProfessionalService" | null;
    legalName: string | null;
    description: string | null;
    streetAddress: string | null;
    city: string | null;
    region: string | null;
    postalCode: string | null;
    country: string | null;
    latitude: number | null;
    longitude: number | null;
    priceRange: "$" | "$$" | "$$$" | null;
    openingHours: Array<string> | null;
    serviceArea: Array<string> | null;
    foundingDate: string | null;
    numberOfEmployees: number | null;
  } | null;
} | null;
// Variable: CONTACT_SECTION_QUERY
// Query: *[_type == "siteSettings"][0]{    contact {      phone,      email,      address    },    contactSection {      heading,      subheading,      ctaLabel,      ctaLink    }  }
export type CONTACT_SECTION_QUERYResult = {
  contact: {
    phone: string | null;
    email: string | null;
    address: string | null;
  } | null;
  contactSection: {
    heading: string | null;
    subheading: string | null;
    ctaLabel: string | null;
    ctaLink: string | null;
  } | null;
} | null;
// Variable: NAVIGATION_QUERY
// Query: *[_type == "navigation"][0]{    mainNav[] {      _key,      label,      "link": link {        linkType,        externalUrl,        openInNewTab,        "internalHref": internalLink->slug.current      },      children[] {        _key,        label,        "link": link {          linkType,          externalUrl,          openInNewTab,          "internalHref": internalLink->slug.current        }      }    },    ctaButton {      label,      "link": link {        linkType,        externalUrl,        openInNewTab,        "internalHref": internalLink->slug.current      }    },    footerColumns[] {      _key,      title,      links[] {        _key,        label,        linkType,        externalUrl,        openInNewTab,        "internalHref": internalLink->slug.current      }    },    legalLinks[] {      _key,      label,      linkType,      externalUrl,      openInNewTab,      "internalHref": internalLink->slug.current    }  }
export type NAVIGATION_QUERYResult = {
  mainNav: Array<{
    _key: string;
    label: string;
    link: {
      linkType: "external" | "internal";
      externalUrl: string | null;
      openInNewTab: boolean | null;
      internalHref: string | null;
    } | null;
    children: Array<{
      _key: string;
      label: string;
      link: {
        linkType: "external" | "internal";
        externalUrl: string | null;
        openInNewTab: boolean | null;
        internalHref: string | null;
      } | null;
    }> | null;
  }> | null;
  ctaButton: {
    label: string | null;
    link: {
      linkType: "external" | "internal";
      externalUrl: string | null;
      openInNewTab: boolean | null;
      internalHref: string | null;
    } | null;
  } | null;
  footerColumns: Array<{
    _key: string;
    title: string;
    links: Array<{
      _key: string;
      label: string;
      linkType: "external" | "internal";
      externalUrl: string | null;
      openInNewTab: boolean | null;
      internalHref: string | null;
    }> | null;
  }> | null;
  legalLinks: Array<{
    _key: string;
    label: string;
    linkType: "external" | "internal";
    externalUrl: string | null;
    openInNewTab: boolean | null;
    internalHref: string | null;
  }> | null;
} | null;
// Variable: ABOUT_PAGE_QUERY
// Query: *[_type == "aboutPage"][0]{    headerEyebrow,    headerTitle,    headerTitleHighlight,    heroTitle,    heroSubtitle,    heroImages[] {      _key,      asset,      alt,      hotspot,      crop    },    enableFullWidthImage,    fullWidthImage {      asset,      alt,      hotspot,      crop    },    missionTitle,    missionIntro,    missionBody,    stats[] {      _key,      label,      value,      postfix    },    teamTitle,    teamDescription,    "seo": {      "title": coalesce(seo.title, heroTitle, "About Us"),      "description": seo.description,      "image": seo.image,      "noIndex": seo.noIndex == true,      "canonicalUrl": seo.canonicalUrl    }  }
export type ABOUT_PAGE_QUERYResult = {
  headerEyebrow: string | null;
  headerTitle: string | null;
  headerTitleHighlight: string | null;
  heroTitle: string;
  heroSubtitle: string | null;
  heroImages: Array<{
    _key: string;
    asset: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    } | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  }> | null;
  enableFullWidthImage: boolean | null;
  fullWidthImage: {
    asset: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    } | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
  missionTitle: string | null;
  missionIntro: string | null;
  missionBody: string | null;
  stats: Array<{
    _key: string;
    label: string;
    value: string;
    postfix: string | null;
  }> | null;
  teamTitle: string | null;
  teamDescription: string | null;
  seo: {
    title: string;
    description: string | null;
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    noIndex: boolean | false;
    canonicalUrl: string | null;
  };
} | null;
// Variable: HOMEPAGE_QUERY
// Query: *[_type == "homepage"][0]{    // Hero Section    heroHeadlinePart1,    heroHighlightWord,    heroHeadlinePart2,    heroDescription,    heroPrimaryCta {      label,      href    },    heroSecondaryCta {      label,      href    },    // Services Section    servicesTitle,    servicesDescription,    serviceCards[] {      _key,      title,      description,      href,      ctaLabel,      image {        asset,        alt,        hotspot,        crop      }    },    // SEO    "seo": {      "title": coalesce(seo.title, "Xuba - IT Solutions"),      "description": seo.description,      "image": seo.image,      "noIndex": seo.noIndex == true,      "canonicalUrl": seo.canonicalUrl    }  }
export type HOMEPAGE_QUERYResult = {
  heroHeadlinePart1: string | null;
  heroHighlightWord: string | null;
  heroHeadlinePart2: string | null;
  heroDescription: string | null;
  heroPrimaryCta: {
    label: string | null;
    href: string | null;
  } | null;
  heroSecondaryCta: {
    label: string | null;
    href: string | null;
  } | null;
  servicesTitle: string | null;
  servicesDescription: string | null;
  serviceCards: Array<{
    _key: string;
    title: string;
    description: string | null;
    href: string | null;
    ctaLabel: string | null;
    image: {
      asset: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      } | null;
      alt: string | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
    } | null;
  }> | null;
  seo: {
    title: string | "Xuba - IT Solutions";
    description: string | null;
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    noIndex: boolean | false;
    canonicalUrl: string | null;
  };
} | null;
// Variable: CONTACT_PAGE_QUERY
// Query: {    "contactPage": *[_type == "contactPage"][0]{      eyebrow,      title,      heading,      description,      responseTimeText,      contactLabels {        addressLabel,        phoneLabel,        emailLabel      },      formSettings {        submitButtonText,        successTitle,        successMessage,        privacyText,        privacyLinkText,        privacyLinkUrl,        privacyAfterText      },      "seo": {        "title": coalesce(seo.title, title, "Contact Us"),        "description": seo.description,        "image": seo.image,        "noIndex": seo.noIndex == true,        "canonicalUrl": seo.canonicalUrl      }    },    "siteSettings": *[_type == "siteSettings"][0]{      contact {        phone,        email,        address      }    }  }
export type CONTACT_PAGE_QUERYResult = {
  contactPage: {
    eyebrow: string | null;
    title: string;
    heading: string | null;
    description: string | null;
    responseTimeText: string | null;
    contactLabels: {
      addressLabel: string | null;
      phoneLabel: string | null;
      emailLabel: string | null;
    } | null;
    formSettings: {
      submitButtonText: string | null;
      successTitle: string | null;
      successMessage: string | null;
      privacyText: string | null;
      privacyLinkText: string | null;
      privacyLinkUrl: string | null;
      privacyAfterText: string | null;
    } | null;
    seo: {
      title: string;
      description: string | null;
      image: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
      noIndex: boolean | false;
      canonicalUrl: string | null;
    };
  } | null;
  siteSettings: {
    contact: {
      phone: string | null;
      email: string | null;
      address: string | null;
    } | null;
  } | null;
};
// Variable: PAGE_QUERY
// Query: *[_type == "page" && slug.current == $slug][0]{    _id,    _type,    title,    "slug": slug.current,    "seo": {      "title": coalesce(seo.title, title),      "description": coalesce(seo.description, ""),      "image": seo.image,      "noIndex": seo.noIndex == true,      "canonicalUrl": seo.canonicalUrl    },    pageBuilder[] {      _key,      _type,      ...,      _type == "servicesGrid" => {        ...,        services[]-> {          _id,          title,          "slug": slug.current,          shortDescription,          icon,          featuredImage        }      },      _type == "teamGrid" => {        ...,        teamMembers[]-> {          _id,          name,          "slug": slug.current,          role,          image,          location,          socialLinks        }      },      _type == "faqSection" => {        ...,        faqs[]-> {          _id,          question,          answer,          category        }      }    }  }
export type PAGE_QUERYResult = {
  _id: string;
  _type: "page";
  title: string;
  slug: string;
  seo: {
    title: string;
    description: string | "";
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    noIndex: boolean | false;
    canonicalUrl: string | null;
  };
  pageBuilder: Array<{
    _key: string;
    _type: "contactSection";
    title?: string;
    subtitle?: string;
    showContactForm?: boolean;
    showContactInfo?: boolean;
    showMap?: boolean;
    backgroundColor?: "accent" | "dark" | "default";
  } | {
    _key: string;
    _type: "faqSection";
    title?: string;
    subtitle?: string;
    faqs: Array<{
      _id: string;
      question: string;
      answer: BlockContent;
      category: "billing" | "general" | "services" | "support" | null;
    }> | null;
    filterByCategory?: "" | "billing" | "general" | "services" | "support";
    limit?: number;
    showContactCta?: boolean;
  } | {
    _key: string;
    _type: "hero";
    title: string;
    subtitle?: string;
    backgroundImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    cta?: Array<{
      label: string;
      link?: Link;
      variant?: "outline" | "primary" | "secondary";
      _type: "ctaButton";
      _key: string;
    }>;
    alignment?: "center" | "left" | "right";
    size?: "full" | "lg" | "md" | "sm";
  } | {
    _key: string;
    _type: "richText";
    title?: string;
    body: BlockContent;
    maxWidth?: "full" | "lg" | "md" | "prose";
    alignment?: "center" | "left";
  } | {
    _key: string;
    _type: "servicesGrid";
    title?: string;
    subtitle?: string;
    services: Array<{
      _id: string;
      title: string;
      slug: string;
      shortDescription: string;
      icon: string | null;
      featuredImage: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
      } | null;
    }> | null;
    showAllLink?: boolean;
    columns?: 2 | 3 | 4;
  } | {
    _key: string;
    _type: "statsSection";
    title?: string;
    subtitle?: string;
    stats?: Array<{
      _key: string;
    } & Stat>;
    backgroundColor?: "accent" | "dark" | "default";
  } | {
    _key: string;
    _type: "teamGrid";
    title?: string;
    subtitle?: string;
    teamMembers: Array<{
      _id: string;
      name: string;
      slug: string;
      role: string;
      image: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
      } | null;
      location: string | null;
      socialLinks: Array<{
        _key: string;
      } & SocialLink> | null;
    }> | null;
    limit?: number;
    showBio?: boolean;
    columns?: 2 | 3 | 4;
  }> | null;
} | null;
// Variable: PAGE_SLUGS_QUERY
// Query: *[_type == "page" && defined(slug.current)]{    "slug": slug.current  }
export type PAGE_SLUGS_QUERYResult = Array<{
  slug: string;
}>;
// Variable: SERVICES_QUERY
// Query: *[_type == "service"] | order(order asc, title asc) {    _id,    title,    "slug": slug.current,    shortDescription,    icon,    featuredImage  }
export type SERVICES_QUERYResult = Array<{
  _id: string;
  title: string;
  slug: string;
  shortDescription: string;
  icon: string | null;
  featuredImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
}>;
// Variable: SERVICE_QUERY
// Query: *[_type == "service" && slug.current == $slug][0]{    _id,    _type,    title,    "slug": slug.current,    shortDescription,    icon,    featuredImage,        // Hero Section    heroImage {      asset,      alt,      hotspot,      crop    },    tagline,    taglineHighlight,    subtitle,        // Introduction Section    introText,    introHighlights,        // Rich Text Body Content    bodyContent,        // Benefits Section    benefitsTitle,    benefitsHighlight,    benefits[] {      _key,      title,      description,      icon    },        // What We Handle Section    servicesTitle,    servicesTitleHighlight,    serviceItems,        // FAQ Section    faqTitle,    faqTitleHighlight,    faqs[] {      _key,      question,      answer    },        // Contact Mini-CTA    contactCta {      enabled,      heading,      buttonText,      buttonLink    },        // CTA Section    ctaHeadline,    ctaHighlight,    ctaSubtext,    ctaButtonText,    ctaButtonLink,        // Related Services (with thumbnails)    relatedServices[]-> {      _id,      title,      "slug": slug.current,      shortDescription,      tagline,      icon,      featuredImage {        asset,        alt,        hotspot,        crop      }    },        // Legacy fields (for backward compatibility)    features[] {      _key,      title,      description,      icon    },    body,        // SEO    "seo": {      "title": coalesce(seo.title, title),      "description": coalesce(seo.description, shortDescription),      "image": coalesce(seo.image, featuredImage),      "noIndex": seo.noIndex == true,      "canonicalUrl": seo.canonicalUrl    }  }
export type SERVICE_QUERYResult = {
  _id: string;
  _type: "service";
  title: string;
  slug: string;
  shortDescription: string;
  icon: string | null;
  featuredImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  heroImage: {
    asset: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    } | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
  tagline: string;
  taglineHighlight: string | null;
  subtitle: string | null;
  introText: string | null;
  introHighlights: Array<string> | null;
  bodyContent: BlockContent | null;
  benefitsTitle: string | null;
  benefitsHighlight: string | null;
  benefits: Array<{
    _key: string;
    title: string;
    description: string | null;
    icon: string | null;
  }> | null;
  servicesTitle: string | null;
  servicesTitleHighlight: string | null;
  serviceItems: Array<string> | null;
  faqTitle: string | null;
  faqTitleHighlight: string | null;
  faqs: Array<{
    _key: string;
    question: string;
    answer: string;
  }> | null;
  contactCta: {
    enabled: boolean | null;
    heading: string | null;
    buttonText: string | null;
    buttonLink: string | null;
  } | null;
  ctaHeadline: string | null;
  ctaHighlight: string | null;
  ctaSubtext: string | null;
  ctaButtonText: string | null;
  ctaButtonLink: string | null;
  relatedServices: Array<{
    _id: string;
    title: string;
    slug: string;
    shortDescription: string;
    tagline: string;
    icon: string | null;
    featuredImage: {
      asset: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      } | null;
      alt: string | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
    } | null;
  }> | null;
  features: Array<{
    _key: string;
    title: string;
    description: string | null;
    icon: string | null;
  }> | null;
  body: BlockContent | null;
  seo: {
    title: string;
    description: string;
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    noIndex: boolean | false;
    canonicalUrl: string | null;
  };
} | null;
// Variable: SERVICE_SLUGS_QUERY
// Query: *[_type == "service" && defined(slug.current)]{    "slug": slug.current  }
export type SERVICE_SLUGS_QUERYResult = Array<{
  slug: string;
}>;
// Variable: OUR_TEAM_PAGE_QUERY
// Query: *[_type == "ourTeamPage"][0]{    headerEyebrow,    headerTitle,    headerTitleHighlight,    headerDescription,    "seo": {      "title": coalesce(seo.title, "Our Team"),      "description": seo.description,      "image": seo.image,      "noIndex": seo.noIndex == true,      "canonicalUrl": seo.canonicalUrl    }  }
export type OUR_TEAM_PAGE_QUERYResult = {
  headerEyebrow: string | null;
  headerTitle: string | null;
  headerTitleHighlight: string | null;
  headerDescription: string | null;
  seo: {
    title: string | "Our Team";
    description: string | null;
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    noIndex: boolean | false;
    canonicalUrl: string | null;
  };
} | null;
// Variable: TEAM_MEMBERS_QUERY
// Query: *[_type == "teamMember" && isActive == true] | order(order asc, name asc) {    _id,    name,    "slug": slug.current,    role,    image,    bio,    location,    email,    socialLinks[] {      _key,      platform,      url    }  }
export type TEAM_MEMBERS_QUERYResult = Array<{
  _id: string;
  name: string;
  slug: string;
  role: string;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  bio: BlockContent | null;
  location: string | null;
  email: string | null;
  socialLinks: Array<{
    _key: string;
    platform: "facebook" | "github" | "instagram" | "linkedin" | "twitter" | "youtube";
    url: string;
  }> | null;
}>;
// Variable: TEAM_MEMBER_QUERY
// Query: *[_type == "teamMember" && slug.current == $slug][0]{    _id,    name,    "slug": slug.current,    role,    image,    bio,    location,    email,    socialLinks[] {      _key,      platform,      url    }  }
export type TEAM_MEMBER_QUERYResult = {
  _id: string;
  name: string;
  slug: string;
  role: string;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  bio: BlockContent | null;
  location: string | null;
  email: string | null;
  socialLinks: Array<{
    _key: string;
    platform: "facebook" | "github" | "instagram" | "linkedin" | "twitter" | "youtube";
    url: string;
  }> | null;
} | null;
// Variable: FAQS_QUERY
// Query: *[_type == "faq" && ($category == "" || category == $category)] | order(order asc) {    _id,    question,    answer,    category  }
export type FAQS_QUERYResult = Array<{
  _id: string;
  question: string;
  answer: BlockContent;
  category: "billing" | "general" | "services" | "support" | null;
}>;
// Variable: TESTIMONIALS_QUERY
// Query: *[_type == "testimonial"] | order(featured desc, order asc) {    _id,    quote,    author,    role,    company,    image,    companyLogo,    featured  }
export type TESTIMONIALS_QUERYResult = Array<{
  _id: string;
  quote: string;
  author: string;
  role: string | null;
  company: string | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  companyLogo: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  featured: boolean | null;
}>;
// Variable: FEATURED_TESTIMONIALS_QUERY
// Query: *[_type == "testimonial" && featured == true] | order(order asc) {    _id,    quote,    author,    role,    company,    image,    companyLogo  }
export type FEATURED_TESTIMONIALS_QUERYResult = Array<{
  _id: string;
  quote: string;
  author: string;
  role: string | null;
  company: string | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  companyLogo: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
}>;
// Variable: SITEMAP_QUERY
// Query: {    "pages": *[_type == "page" && !(seo.noIndex == true) && defined(slug.current)]{      "slug": slug.current,      _updatedAt    },    "services": *[_type == "service" && !(seo.noIndex == true) && defined(slug.current)]{      "slug": slug.current,      _updatedAt    }  }
export type SITEMAP_QUERYResult = {
  pages: Array<{
    slug: string;
    _updatedAt: string;
  }>;
  services: Array<{
    slug: string;
    _updatedAt: string;
  }>;
};
// Variable: TERMS_OF_SERVICE_QUERY
// Query: *[_type == "termsOfServicePage"][0]{    eyebrow,    title,    titleHighlight,    lastUpdated,    body,    seo {      title,      description,      "image": image.asset,      noIndex,      canonicalUrl    }  }
export type TERMS_OF_SERVICE_QUERYResult = {
  eyebrow: string | null;
  title: string;
  titleHighlight: string | null;
  lastUpdated: string | null;
  body: BlockContent;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    } | null;
    noIndex: boolean | null;
    canonicalUrl: string | null;
  } | null;
} | null;
// Variable: PRIVACY_POLICY_QUERY
// Query: *[_type == "privacyPolicyPage"][0]{    eyebrow,    title,    titleHighlight,    lastUpdated,    body,    seo {      title,      description,      "image": image.asset,      noIndex,      canonicalUrl    }  }
export type PRIVACY_POLICY_QUERYResult = {
  eyebrow: string | null;
  title: string;
  titleHighlight: string | null;
  lastUpdated: string | null;
  body: BlockContent;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    } | null;
    noIndex: boolean | null;
    canonicalUrl: string | null;
  } | null;
} | null;
// Variable: SERVICES_PAGE_QUERY
// Query: *[_type == "servicesPage"][0]{    eyebrow,    title,    titleHighlight,    description,    seo {      title,      description,      "image": image.asset,      noIndex,      canonicalUrl    }  }
export type SERVICES_PAGE_QUERYResult = {
  eyebrow: string | null;
  title: string;
  titleHighlight: string | null;
  description: string | null;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    } | null;
    noIndex: boolean | null;
    canonicalUrl: string | null;
  } | null;
} | null;
// Variable: SUPPORT_PAGE_QUERY
// Query: *[_type == "supportPage"][0]{    eyebrow,    title,    titleHighlight,    description,    teamViewerUrl,    teamViewerTitle,    seo {      title,      description,      "image": image.asset,      noIndex,      canonicalUrl    }  }
export type SUPPORT_PAGE_QUERYResult = {
  eyebrow: string | null;
  title: string;
  titleHighlight: string | null;
  description: string | null;
  teamViewerUrl: string;
  teamViewerTitle: string | null;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    } | null;
    noIndex: boolean | null;
    canonicalUrl: string | null;
  } | null;
} | null;
// Variable: REDIRECTS_QUERY
// Query: *[_type == "redirect" && isEnabled == true]{    source,    destination,    permanent  }
export type REDIRECTS_QUERYResult = Array<{
  source: string;
  destination: string;
  permanent: boolean | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n  *[_type == \"service\" && defined(slug.current)] | order(title asc) {\n    \"slug\": slug.current,\n    _updatedAt\n  }\n": SITEMAP_SERVICES_QUERYResult;
    "\n  *[_type == \"siteSettings\"][0]{\n    siteName,\n    logo,\n    favicon,\n    \"defaultSeo\": {\n      \"title\": coalesce(defaultSeo.title, siteName),\n      \"description\": defaultSeo.description,\n      \"image\": defaultSeo.image,\n      \"noIndex\": defaultSeo.noIndex == true\n    },\n    contact {\n      phone,\n      email,\n      address,\n      businessHours\n    },\n    socialLinks[] {\n      _key,\n      platform,\n      url\n    },\n    analytics {\n      googleAnalyticsId,\n      googleTagManagerId\n    },\n    contactSection {\n      heading,\n      subheading,\n      ctaLabel,\n      ctaLink\n    },\n    localBusiness {\n      businessType,\n      legalName,\n      description,\n      streetAddress,\n      city,\n      region,\n      postalCode,\n      country,\n      latitude,\n      longitude,\n      priceRange,\n      openingHours,\n      serviceArea,\n      foundingDate,\n      numberOfEmployees\n    }\n  }\n": SITE_SETTINGS_QUERYResult;
    "\n  *[_type == \"siteSettings\"][0]{\n    contact {\n      phone,\n      email,\n      address\n    },\n    contactSection {\n      heading,\n      subheading,\n      ctaLabel,\n      ctaLink\n    }\n  }\n": CONTACT_SECTION_QUERYResult;
    "\n  *[_type == \"navigation\"][0]{\n    mainNav[] {\n      _key,\n      label,\n      \"link\": link {\n        linkType,\n        externalUrl,\n        openInNewTab,\n        \"internalHref\": internalLink->slug.current\n      },\n      children[] {\n        _key,\n        label,\n        \"link\": link {\n          linkType,\n          externalUrl,\n          openInNewTab,\n          \"internalHref\": internalLink->slug.current\n        }\n      }\n    },\n    ctaButton {\n      label,\n      \"link\": link {\n        linkType,\n        externalUrl,\n        openInNewTab,\n        \"internalHref\": internalLink->slug.current\n      }\n    },\n    footerColumns[] {\n      _key,\n      title,\n      links[] {\n        _key,\n        label,\n        linkType,\n        externalUrl,\n        openInNewTab,\n        \"internalHref\": internalLink->slug.current\n      }\n    },\n    legalLinks[] {\n      _key,\n      label,\n      linkType,\n      externalUrl,\n      openInNewTab,\n      \"internalHref\": internalLink->slug.current\n    }\n  }\n": NAVIGATION_QUERYResult;
    "\n  *[_type == \"aboutPage\"][0]{\n    headerEyebrow,\n    headerTitle,\n    headerTitleHighlight,\n    heroTitle,\n    heroSubtitle,\n    heroImages[] {\n      _key,\n      asset,\n      alt,\n      hotspot,\n      crop\n    },\n    enableFullWidthImage,\n    fullWidthImage {\n      asset,\n      alt,\n      hotspot,\n      crop\n    },\n    missionTitle,\n    missionIntro,\n    missionBody,\n    stats[] {\n      _key,\n      label,\n      value,\n      postfix\n    },\n    teamTitle,\n    teamDescription,\n    \"seo\": {\n      \"title\": coalesce(seo.title, heroTitle, \"About Us\"),\n      \"description\": seo.description,\n      \"image\": seo.image,\n      \"noIndex\": seo.noIndex == true,\n      \"canonicalUrl\": seo.canonicalUrl\n    }\n  }\n": ABOUT_PAGE_QUERYResult;
    "\n  *[_type == \"homepage\"][0]{\n    // Hero Section\n    heroHeadlinePart1,\n    heroHighlightWord,\n    heroHeadlinePart2,\n    heroDescription,\n    heroPrimaryCta {\n      label,\n      href\n    },\n    heroSecondaryCta {\n      label,\n      href\n    },\n    // Services Section\n    servicesTitle,\n    servicesDescription,\n    serviceCards[] {\n      _key,\n      title,\n      description,\n      href,\n      ctaLabel,\n      image {\n        asset,\n        alt,\n        hotspot,\n        crop\n      }\n    },\n    // SEO\n    \"seo\": {\n      \"title\": coalesce(seo.title, \"Xuba - IT Solutions\"),\n      \"description\": seo.description,\n      \"image\": seo.image,\n      \"noIndex\": seo.noIndex == true,\n      \"canonicalUrl\": seo.canonicalUrl\n    }\n  }\n": HOMEPAGE_QUERYResult;
    "\n  {\n    \"contactPage\": *[_type == \"contactPage\"][0]{\n      eyebrow,\n      title,\n      heading,\n      description,\n      responseTimeText,\n      contactLabels {\n        addressLabel,\n        phoneLabel,\n        emailLabel\n      },\n      formSettings {\n        submitButtonText,\n        successTitle,\n        successMessage,\n        privacyText,\n        privacyLinkText,\n        privacyLinkUrl,\n        privacyAfterText\n      },\n      \"seo\": {\n        \"title\": coalesce(seo.title, title, \"Contact Us\"),\n        \"description\": seo.description,\n        \"image\": seo.image,\n        \"noIndex\": seo.noIndex == true,\n        \"canonicalUrl\": seo.canonicalUrl\n      }\n    },\n    \"siteSettings\": *[_type == \"siteSettings\"][0]{\n      contact {\n        phone,\n        email,\n        address\n      }\n    }\n  }\n": CONTACT_PAGE_QUERYResult;
    "\n  *[_type == \"page\" && slug.current == $slug][0]{\n    _id,\n    _type,\n    title,\n    \"slug\": slug.current,\n    \"seo\": {\n      \"title\": coalesce(seo.title, title),\n      \"description\": coalesce(seo.description, \"\"),\n      \"image\": seo.image,\n      \"noIndex\": seo.noIndex == true,\n      \"canonicalUrl\": seo.canonicalUrl\n    },\n    pageBuilder[] {\n      _key,\n      _type,\n      ...,\n      _type == \"servicesGrid\" => {\n        ...,\n        services[]-> {\n          _id,\n          title,\n          \"slug\": slug.current,\n          shortDescription,\n          icon,\n          featuredImage\n        }\n      },\n      _type == \"teamGrid\" => {\n        ...,\n        teamMembers[]-> {\n          _id,\n          name,\n          \"slug\": slug.current,\n          role,\n          image,\n          location,\n          socialLinks\n        }\n      },\n      _type == \"faqSection\" => {\n        ...,\n        faqs[]-> {\n          _id,\n          question,\n          answer,\n          category\n        }\n      }\n    }\n  }\n": PAGE_QUERYResult;
    "\n  *[_type == \"page\" && defined(slug.current)]{\n    \"slug\": slug.current\n  }\n": PAGE_SLUGS_QUERYResult;
    "\n  *[_type == \"service\"] | order(order asc, title asc) {\n    _id,\n    title,\n    \"slug\": slug.current,\n    shortDescription,\n    icon,\n    featuredImage\n  }\n": SERVICES_QUERYResult;
    "\n  *[_type == \"service\" && slug.current == $slug][0]{\n    _id,\n    _type,\n    title,\n    \"slug\": slug.current,\n    shortDescription,\n    icon,\n    featuredImage,\n    \n    // Hero Section\n    heroImage {\n      asset,\n      alt,\n      hotspot,\n      crop\n    },\n    tagline,\n    taglineHighlight,\n    subtitle,\n    \n    // Introduction Section\n    introText,\n    introHighlights,\n    \n    // Rich Text Body Content\n    bodyContent,\n    \n    // Benefits Section\n    benefitsTitle,\n    benefitsHighlight,\n    benefits[] {\n      _key,\n      title,\n      description,\n      icon\n    },\n    \n    // What We Handle Section\n    servicesTitle,\n    servicesTitleHighlight,\n    serviceItems,\n    \n    // FAQ Section\n    faqTitle,\n    faqTitleHighlight,\n    faqs[] {\n      _key,\n      question,\n      answer\n    },\n    \n    // Contact Mini-CTA\n    contactCta {\n      enabled,\n      heading,\n      buttonText,\n      buttonLink\n    },\n    \n    // CTA Section\n    ctaHeadline,\n    ctaHighlight,\n    ctaSubtext,\n    ctaButtonText,\n    ctaButtonLink,\n    \n    // Related Services (with thumbnails)\n    relatedServices[]-> {\n      _id,\n      title,\n      \"slug\": slug.current,\n      shortDescription,\n      tagline,\n      icon,\n      featuredImage {\n        asset,\n        alt,\n        hotspot,\n        crop\n      }\n    },\n    \n    // Legacy fields (for backward compatibility)\n    features[] {\n      _key,\n      title,\n      description,\n      icon\n    },\n    body,\n    \n    // SEO\n    \"seo\": {\n      \"title\": coalesce(seo.title, title),\n      \"description\": coalesce(seo.description, shortDescription),\n      \"image\": coalesce(seo.image, featuredImage),\n      \"noIndex\": seo.noIndex == true,\n      \"canonicalUrl\": seo.canonicalUrl\n    }\n  }\n": SERVICE_QUERYResult;
    "\n  *[_type == \"service\" && defined(slug.current)]{\n    \"slug\": slug.current\n  }\n": SERVICE_SLUGS_QUERYResult;
    "\n  *[_type == \"ourTeamPage\"][0]{\n    headerEyebrow,\n    headerTitle,\n    headerTitleHighlight,\n    headerDescription,\n    \"seo\": {\n      \"title\": coalesce(seo.title, \"Our Team\"),\n      \"description\": seo.description,\n      \"image\": seo.image,\n      \"noIndex\": seo.noIndex == true,\n      \"canonicalUrl\": seo.canonicalUrl\n    }\n  }\n": OUR_TEAM_PAGE_QUERYResult;
    "\n  *[_type == \"teamMember\" && isActive == true] | order(order asc, name asc) {\n    _id,\n    name,\n    \"slug\": slug.current,\n    role,\n    image,\n    bio,\n    location,\n    email,\n    socialLinks[] {\n      _key,\n      platform,\n      url\n    }\n  }\n": TEAM_MEMBERS_QUERYResult;
    "\n  *[_type == \"teamMember\" && slug.current == $slug][0]{\n    _id,\n    name,\n    \"slug\": slug.current,\n    role,\n    image,\n    bio,\n    location,\n    email,\n    socialLinks[] {\n      _key,\n      platform,\n      url\n    }\n  }\n": TEAM_MEMBER_QUERYResult;
    "\n  *[_type == \"faq\" && ($category == \"\" || category == $category)] | order(order asc) {\n    _id,\n    question,\n    answer,\n    category\n  }\n": FAQS_QUERYResult;
    "\n  *[_type == \"testimonial\"] | order(featured desc, order asc) {\n    _id,\n    quote,\n    author,\n    role,\n    company,\n    image,\n    companyLogo,\n    featured\n  }\n": TESTIMONIALS_QUERYResult;
    "\n  *[_type == \"testimonial\" && featured == true] | order(order asc) {\n    _id,\n    quote,\n    author,\n    role,\n    company,\n    image,\n    companyLogo\n  }\n": FEATURED_TESTIMONIALS_QUERYResult;
    "\n  {\n    \"pages\": *[_type == \"page\" && !(seo.noIndex == true) && defined(slug.current)]{\n      \"slug\": slug.current,\n      _updatedAt\n    },\n    \"services\": *[_type == \"service\" && !(seo.noIndex == true) && defined(slug.current)]{\n      \"slug\": slug.current,\n      _updatedAt\n    }\n  }\n": SITEMAP_QUERYResult;
    "\n  *[_type == \"termsOfServicePage\"][0]{\n    eyebrow,\n    title,\n    titleHighlight,\n    lastUpdated,\n    body,\n    seo {\n      title,\n      description,\n      \"image\": image.asset,\n      noIndex,\n      canonicalUrl\n    }\n  }\n": TERMS_OF_SERVICE_QUERYResult;
    "\n  *[_type == \"privacyPolicyPage\"][0]{\n    eyebrow,\n    title,\n    titleHighlight,\n    lastUpdated,\n    body,\n    seo {\n      title,\n      description,\n      \"image\": image.asset,\n      noIndex,\n      canonicalUrl\n    }\n  }\n": PRIVACY_POLICY_QUERYResult;
    "\n  *[_type == \"servicesPage\"][0]{\n    eyebrow,\n    title,\n    titleHighlight,\n    description,\n    seo {\n      title,\n      description,\n      \"image\": image.asset,\n      noIndex,\n      canonicalUrl\n    }\n  }\n": SERVICES_PAGE_QUERYResult;
    "\n  *[_type == \"supportPage\"][0]{\n    eyebrow,\n    title,\n    titleHighlight,\n    description,\n    teamViewerUrl,\n    teamViewerTitle,\n    seo {\n      title,\n      description,\n      \"image\": image.asset,\n      noIndex,\n      canonicalUrl\n    }\n  }\n": SUPPORT_PAGE_QUERYResult;
    "\n  *[_type == \"redirect\" && isEnabled == true]{\n    source,\n    destination,\n    permanent\n  }\n": REDIRECTS_QUERYResult;
  }
}
